CREATE TABLE IF NOT EXISTS UserData (
    User_ID SERIAL PRIMARY KEY,
    Username VARCHAR(255),
    Pass VARCHAR(255),
    Langg VARCHAR(255),
    Age INT,
    Email_ID VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS GPC (
    GPC_ID SERIAL PRIMARY KEY,
    GPC_Name VARCHAR(255),
    Email_ID VARCHAR(255) 
);

CREATE TABLE IF NOT EXISTS Game (
    Game_ID SERIAL PRIMARY KEY,
    Game_Name VARCHAR(255),
    Price DECIMAL(10, 2),
    GPC_ID SERIAL,
    Game_Release_Date DATE,
    Age_Limit INT,
    FOREIGN KEY (GPC_ID) REFERENCES GPC(GPC_ID)
);

CREATE TABLE IF NOT EXISTS UserGames (
    User_ID SERIAL,
    Game_ID SERIAL,
    FOREIGN KEY (User_ID) REFERENCES UserData(User_ID),
    FOREIGN KEY (Game_ID) REFERENCES Game(Game_ID),
    PRIMARY KEY (User_ID, Game_ID)
);

CREATE TABLE IF NOT EXISTS Region (
    RegionID SERIAL PRIMARY KEY,
    Region_Name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS User_Region (
    RegionID SERIAL,
    User_Name VARCHAR(255),
    FOREIGN KEY (RegionID) REFERENCES Region(RegionID),
    PRIMARY KEY (RegionID, User_Name)
);

CREATE TABLE IF NOT EXISTS Game_Region (
    RegionID SERIAL,
    Game_Name VARCHAR(255),
    FOREIGN KEY (RegionID) REFERENCES Region(RegionID),
    PRIMARY KEY (RegionID, Game_Name)
);

CREATE TABLE IF NOT EXISTS Review (
    User_ID SERIAL,
    Game_ID SERIAL,
    Posted_Time TIMESTAMP,
    Content VARCHAR(100),
    FOREIGN KEY (User_ID) REFERENCES UserData(User_ID),
    FOREIGN KEY (Game_ID) REFERENCES Game(Game_ID),
    PRIMARY KEY (User_ID, Game_ID)
);

CREATE TABLE IF NOT EXISTS Genre (
    Genre_ID SERIAL PRIMARY KEY,
    Genre_Name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS Game_Genre (
    Genre_ID SERIAL,
    Game_ID SERIAL,
    FOREIGN KEY (Genre_ID) REFERENCES Genre(Genre_ID),
    FOREIGN KEY (Game_ID) REFERENCES Game(Game_ID),
    PRIMARY KEY (Genre_ID, Game_ID)
);

CREATE TABLE IF NOT EXISTS Lang (
    Lang_ID SERIAL PRIMARY KEY,
    Lang_Name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS Game_Lang (
    Lang_ID SERIAL,
    Game_ID SERIAL,
    FOREIGN KEY (Lang_ID) REFERENCES Lang(Lang_ID),
    FOREIGN KEY (Game_ID) REFERENCES Game(Game_ID),
    PRIMARY KEY (Lang_ID, Game_ID)
);
